UI/WebStore/Areas/Admin/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Entities.Identity;
using WebStore.Services.Interfaces;

namespace WebStore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = Role.Administrators)]
    public class ProductsController : Controller
    {
        private readonly IProductData _ProductData;

        public ProductsController(IProductData ProductData) => _ProductData = ProductData;

        public IActionResult Index() => View(_ProductData.GetProducts());

        public IActionResult Edit(int id) =>
            _ProductData.GetProductById(id) is { } product
                ? View(product)
                : NotFound();

        public IActionResult Delete(int id) =>
            _ProductData.GetProductById(id) is { } product
                ? View(product)
                : NotFound();
    }
}

UI/WebStore/Components/BrandsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Services.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Components
{
    public class BrandsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BrandsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke() => View(GetBrands());
            
        public IEnumerable<BrandViewModel> GetBrands() =>
            _ProductData.GetBrands()
               .OrderBy(b => b.Order)
               .Select(b => new BrandViewModel
                {
                    Id = b.Id,
                    Name = b.Name,
                });
    }
}

UI/WebStore/Components/SectionsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebStore.Services.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Components
{
    //[ViewComponent(Name = "Sections")]
    public class SectionsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public SectionsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke()
        {
            var sections = _ProductData.GetSections();

            var parent_sections = sections.Where(s => s.ParentId == null);

            var parent_sections_views = parent_sections
               .Select(s => new SectionViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Order = s.Order,
                })
               .ToList();

            foreach (var parent_section in parent_sections_views)
            {
                var childs = sections.Where(s => s.ParentId == parent_section.Id);

                foreach (var child_section in childs)
                    parent_section.ChildSections.Add(new SectionViewModel
                    {
                        Id = child_section.Id,
                        Name = child_section.Name,
                        Order = child_section.Order,
                        Parent = parent_section,
                    });

                parent_section.ChildSections.Sort((a, b) => Comparer<int>.Default.Compare(a.Order, b.Order));
            }

            parent_sections_views.Sort((a, b) => Comparer<int>.Default.Compare(a.Order, b.Order));

            return View(parent_sections_views);
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using WebStore.Domain;
using WebStore.Infrastructure.Mapping;
using WebStore.Services.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly IProductData _ProductData;

        public CatalogController(IProductData ProductData) => _ProductData = ProductData;

        public IActionResult Index(int? BrandId, int? SectionId)
        {
            var filter = new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId,
            };

            var products = _ProductData.GetProducts(filter);

            return View(new CatalogViewModel
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Products = products.OrderBy(p => p.Order).ToView()
            });
        }

        public IActionResult Details(int Id)
        {
            var product = _ProductData.GetProductById(Id);
            if (product is null)
                return NotFound();

            //return View(new ProductViewModel
            //{
            //    Id = product.Id,
            //    Name = product.Name,
            //    Price = product.Price,
            //    ImageUrl = product.ImageUrl,
            //});
            return View(product.ToView());
        }
    }
}

UI/WebStore/Controllers/EmployeesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
//using WebStore.Domain.Entities;
using WebStore.Domain.Models;
using WebStore.Domain.Entities.Identity;
using WebStore.Services.Interfaces;
using WebStore.ViewModels;

namespace WebStore.Controllers
{
    //[Route("Staff")]
    //[Route("Employees")]
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly IEmployeesData _EmployeesData;
        private readonly ILogger<EmployeesController> _Logger;

        public EmployeesController(IEmployeesData EmployeesData, ILogger<EmployeesController> Logger)
        {
            _EmployeesData = EmployeesData;
            _Logger = Logger;
        }

        //[Route("all")]
        public IActionResult Index() => View(_EmployeesData.GetAll());

        //[Route("info/{id}")]
        //[Route("info-id-{id}")]
        public IActionResult Details(int id)
        {
            var employee = _EmployeesData.Get(id);

            if (employee == null)
                return NotFound();

            return View(employee);
        }

        [Authorize(Roles = Role.Administrators)]
        public IActionResult Create() => View("Edit", new EmployeeViewModel());

        [Authorize(Roles = Role.Administrators)]
        public IActionResult Edit(int? id)
        {
            if (id is null)
                return View(new EmployeeViewModel());

            var employee = _EmployeesData.Get((int)id);
            if (employee is null)
                return NotFound();

            var view_model = new EmployeeViewModel
            {
                Id = employee.Id,
                LastName = employee.LastName,
                Name = employee.FirstName,
                Patronymic = employee.Patronymic,
                Age = employee.Age,
            };
            return View(view_model);
        }

        [HttpPost]
        [Authorize(Roles = Role.Administrators)]
        public IActionResult Edit(EmployeeViewModel Model)
        {
            if (Model.LastName == "Qwe")
                ModelState.AddModelError("LastName", "Qwe - плохое имя!");

            if (Model.LastName == "Asd" && Model.Name == "Qwe")
                ModelState.AddModelError("", "Странное сочетание имени и фамилии");

            if (!ModelState.IsValid)
                return View(Model);

            _Logger.LogInformation("Редактирование сотрудника id:{0}", Model.Id);

            var employee = new Employee
            {
                Id = Model.Id,
                LastName = Model.LastName,
                FirstName = Model.Name,
                Patronymic = Model.Patronymic,
                Age = Model.Age,
            };

            if (employee.Id == 0)
                _EmployeesData.Add(employee);
            else
                _EmployeesData.Update(employee);

            _Logger.LogInformation("Редактирование сотрудника id:{0} завершено", Model.Id);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = Role.Administrators)]
        public IActionResult Delete(int id)
        {
            if (id <= 0) return BadRequest();

            var employee = _EmployeesData.Get(id);
            if (employee is null)
                return NotFound();

            return View(new EmployeeViewModel
            {
                Id = employee.Id,
                LastName = employee.LastName,
                Name = employee.FirstName,
                Patronymic = employee.Patronymic,
                Age = employee.Age,
            });
        }

        [HttpPost]
        [Authorize(Roles = Role.Administrators)]
        public IActionResult DeleteConfirmed(int id)
        {
            _Logger.LogInformation("Удаление сотрудника id:{0}", id);

            _EmployeesData.Delete(id);

            _Logger.LogInformation("Удаление сотрудника id:{0} завершено", id);
            return RedirectToAction("Index");
        }
    }
}

UI/WebStore/Views/Shared/Partial/_CategoryTab.cshtml
<div class="category-tab">
    <!--category-tab-->
    <div class="col-sm-12">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tshirt" data-toggle="tab">Рубашки</a></li>
            <li><a href="#blazers" data-toggle="tab">Blazers</a></li>
            <li><a href="#sunglass" data-toggle="tab">Sunglass</a></li>
            <li><a href="#kids" data-toggle="tab">Детские</a></li>
            <li><a href="#poloshirt" data-toggle="tab">Polo shirt</a></li>
        </ul>
    </div>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="tshirt">
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="blazers">
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="sunglass">
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="kids">
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="poloshirt">
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery2.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery4.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery3.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <div class="productinfo text-center">
                            <img src="~/images/home/gallery1.jpg" alt="" />
                            <h2>$56</h2>
                            <p>Лёгкое чёрное поло</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>В корзину</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--/category-tab-->

UI/WebStore/Views/Shared/Partial/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +7(123)456-78-90</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.ru</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a asp-controller="Home" asp-action="Index"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                США
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Канада</a></li>
                                <li><a href="#">Англия</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                Доллар
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Канадский доллар</a></li>
                                <li><a href="#">Фунт</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <vc:user-info/>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <partial name="Partial/_MainMenu"/>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->

UI/WebStore/Views/Shared/Partial/_LeftSideBar.cshtml
<div class="left-sidebar">

    @*@await Component.InvokeAsync("Sections")*@
    <vc:sections/>
    
    <vc:brands/>

    <div class="price-range">
        <!--price-range-->
        <h2>Цены</h2>
        <div class="well text-center">
            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br/>
            <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center">
        <!--shipping-->
        <img src="~/images/home/shipping.jpg" alt=""/>
    </div><!--/shipping-->

</div>

UI/WebStore/Views/Shared/Partial/_MainMenu.cshtml
<div class="mainmenu pull-left">
    <ul class="nav navbar-nav collapse navbar-collapse">
        <li><a asp-controller="Home" asp-action="Index" class="active">Home</a></li>
        <li class="dropdown">
            <a href="#">Магазин<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a asp-controller="Catalog" asp-action="Index">Каталог</a></li>
                <li><a href="product-details.html">О товаре</a></li>
                <li><a href="checkout.html">Оформить заказ</a></li>
                <li><a href="cart.html">Корзина</a></li>
                <li><a href="login.html">Вход</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#">Блог<i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
                <li><a asp-controller="Home" asp-action="Blog">Список блогов</a></li>
                <li><a href="blog-single.html">Блог магазина</a></li>
            </ul>
        </li>
        <li><a href="404.html">404</a></li>
        <li><a href="contact-us.html">Контакты</a></li>
        <li><a asp-controller="Employees" asp-action="Index">Сотрудники</a></li>
    </ul>
</div>

UI/WebStore/Views/Shared/Partial/_Products.cshtml
@model IEnumerable<WebStore.ViewModels.ProductViewModel>

<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Товары</h2>
    
    @foreach (var product in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/images/shop/@product.ImageUrl" alt="@product.Name" />
                        <h2>@product.Price.ToString("C")</h2>
                        <p>
                            <a asp-controller="Catalog" asp-action="Details" asp-route-Id="@product.Id">@product.Name</a>
                        </p>
                        <a asp-controller="Cart" asp-action="Add" asp-route-id="@product.Id" 
                           class="btn btn-default add-to-cart">
                            <i class="fa fa-shopping-cart"></i>
                            В корзину
                        </a>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@product.Price.ToString("C")</h2>
                            <p>
                                <a asp-controller="Catalog" asp-action="Details" asp-route-Id="@product.Id">@product.Name</a>
                            </p>
                            <a asp-controller="Cart" asp-action="Add" asp-route-id="@product.Id" 
                               class="btn btn-default add-to-cart">
                                <i class="fa fa-shopping-cart"></i>
                                В корзину
                            </a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить в желания</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Добавить к сравнению</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }
   

</div><!--features_items-->

UI/WebStore/Views/Shared/Partial/_Scripts.cshtml
<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery.scrollUp.min.js"></script>
<script src="~/js/jquery.prettyPhoto.js"></script>

<environment include="Development">
    <script src="~/js/price-range.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
</environment>

<environment exclude="Development">
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

UI/WebStore/Views/Shared/Partial/_Styles.cshtml
<link href="~/css/bootstrap.min.css" rel="stylesheet">
<link href="~/css/font-awesome.min.css" rel="stylesheet">
<link href="~/css/prettyPhoto.css" rel="stylesheet">

<environment include="Development">
    <link href="~/css/price-range.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/responsive.css" rel="stylesheet">
</environment>

<environment exclude="Development">
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true">
</environment>

<!--[if lt IE 9]>
    <script src="~/js/html5shiv.js"></script>
    <script src="~/js/respond.min.js"></script>
<![endif]-->